---
version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      - PASSWORD=password
      - PROXY_DOMAIN=code.bad-gateway.online
      - DEFAULT_WORKSPACE=/workspace 
    volumes:
      - /workspace:/workspace
    ports:
      - 8443:8443
    restart: unless-stopped
